### ISSUE TITLE
Final work before releasing v2

### ISSUE THREAD

**Issue by viktorstrate** [photoview/photoview#168]
### Additions
- [x] Migrate the maps page with the new database integration. (assigned @stz184 #175)

### Bugfixes
- [x] Scan All button doesn't work (assigned @stz184)
- [x] Add new user from settings page doesn't work (assigned @stz184 #171)
- [x] Delete users from settings page doesn't work (assigned @stz184 #172)
- [x] Videos doesn't seem to work
- [x] EXIF data doesn't show up
- [x] Fix search
- [x] Fix favorites

#### Compatibility error with Gorm and MariaDB when running in Docker
- [x] Fix this problem

This seems to be a periodic error, sometimes when inserting to the database the errors below is thrown.

<details><summary>See error logs regarding this problem</summary>
<p>

```
photoview_1  | 2021/01/17 21:24:58 /app/scanner/scanner_album.go:42 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 1
photoview_1  | [0.507ms] [rows:0] INSERT INTO `users` (`created_at`,`updated_at`,`username`,`password`,`admin`,`id`) VALUES ('2021-01-17 21:24:58.164','2021-01-17 21:24:58.164','viktorstrate','$2a$12$6ketlL58FgVIjtITQpaBh.CAFF5dciorwa/5td8UdKqGua8QwrxDm',true,1) ON CONFLICT DO NOTHING
photoview_1  |
photoview_1  | 2021/01/17 21:24:58 /app/scanner/scanner_album.go:42 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 1
photoview_1  | [0.734ms] [rows:0] INSERT INTO `user_albums` (`album_id`,`user_id`) VALUES (1,1) ON CONFLICT DO NOTHING
photoview_1  |
photoview_1  | 2021/01/17 21:24:58 /app/scanner/scanner_album.go:42 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 1; Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 1
photoview_1  | [2.828ms] [rows:1] INSERT INTO `albums` (`created_at`,`updated_at`,`title`,`parent_album_id`,`path`,`path_hash`) VALUES ('2021-01-17 21:24:58.166','2021-01-17 21:24:58.166','/',NULL,'/','6666cd76f96956469e7be39d750cc7d9')
photoview_1  | runtime error: invalid memory address or nil pointer dereference
photoview_1  |
photoview_1  | goroutine 50 [running]:
photoview_1  | runtime/debug.Stack(0x1, 0x0, 0x0)
photoview_1  | 	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
photoview_1  | runtime/debug.PrintStack()
photoview_1  | 	/usr/lib/go/src/runtime/debug/stack.go:16 +0x25
photoview_1  | github.com/99designs/gqlgen/graphql.DefaultRecover(0xcac160, 0xc000422c00, 0xb43840, 0xfddf00, 0x760f6b, 0xc000300270)
```

</p>
</details>

#### User albums foreign key constraint error
- [x] Investigate and fix (solved with 9afacc3)

```
Could not delete old albums from database: Error 1451: Cannot delete or update a parent row: a foreign key constraint fails (`photoview`.`user_albums`, CONSTRAINT `fk_user_albums_album` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`)) 
```

#### Make sure child albums of paths shared across users are correctly added to the database
- [x] If a new user is added to a path that already is owned by another user, make sure that all subpaths are added to the new user as well to the `user_albums` table.

**Comment by stz184** [comment]
I am starting work on the 1st 3 bullets.

**Comment by stz184** [comment]
**About the 1s bug:  Scan All button doesn't work (assigned @stz184)**
Actually, the button works as expected. At least on backend level because when it is clicked, a graphql call is made and the scanner is triggered (I already checked this and found no backend issues). 
The real problem is that the webscocket gets disconnected after awhile despite the keep alive calls. That's why I observed the following behavior:
1) If you login to the system and go straight to Settings -> Scan All, you will receive notifications about the progress of the scanner immediately. The socket connection hasn't dropped yet and it is still alive. If the scanner continues working long enough, you will probably miss the notification about its completion because the socket connection will drop before that.
2) If you login to the system and wait 30+ seconds before you hit Scan All button, you will probably not receive anything as notifications so you will be misled that the button doesn't work. If you hit the refresh button on the browser, a new websocket connection will be established and you will see the progress of the scanner.

The issue is most probably caused by the problem described here https://github.com/99designs/gqlgen/issues/1179
I already tried to bump apollo/client version from 3.3.4 to 3.3.7 but the issue is still reproducible. 

![Screenshot from 2021-01-25 10-01-38](https://user-images.githubusercontent.com/3320562/105679835-aa2de680-5ef7-11eb-87e1-6add984812ed.png)

**Comment by viktorstrate** [comment]
Okay, thank you for the detailed description. I've noticed this as well, but I haven't look into it.
I will watch the issue you linked for updates.

**Comment by stz184** [comment]
I just committed the code for the maps page. Excuse me for the delay.
https://github.com/photoview/photoview/pull/175

**Comment by viktorstrate** [comment]
Awesome, no problem with the delay. It looks like a bigger task than I expected.

I will take a proper look later today.

**Comment by viktorstrate** [comment]
Every task is now completed, I will give it a proper test run to maybe catch some obvious bugs then release v2 if everything looks good.
